// @ts-nocheck
'use client';

import Head from 'next/head';
import dynamic from 'next/dynamic';
import 'smart-webcomponents-react/source/styles/smart.default.css';
import styles from './calendar.module.css';
import { useEffect, useState } from 'react';

export default function Calendar() {
    const [DynamicScheduler, setDynamicScheduler] = useState<any>(() => null); // Initialize with a function

    useEffect(() => {
        // Load the Smart.Scheduler component dynamically only in the browser
        import('smart-webcomponents-react/scheduler').then(module => {
            setDynamicScheduler(() => module.Scheduler); // Use module.Scheduler to access the Scheduler component
        });
    }, []);

    // Return loading state if the component is not yet loaded
    if (!DynamicScheduler) return <div>Loading...</div>;

    const today = new Date(),
        todayDate = today.getDate(),
        currentYear = today.getFullYear(),
        currentMonth = today.getMonth(),
        dataSource = [
            {
                label: 'Google AdWords Strategy',
                dateStart: new Date(currentYear, currentMonth, todayDate, 9, 0),
                dateEnd: new Date(currentYear, currentMonth, todayDate, 10, 30),
                backgroundColor: '#E67C73'
            },
            {
                label: 'New Brochures',
                dateStart: new Date(currentYear, currentMonth, todayDate - 1, 11, 30),
                dateEnd: new Date(currentYear, currentMonth, todayDate - 1, 14, 15),
                backgroundColor: '#8E24AA'
            },
            {
                label: 'Brochure Design Review',
                dateStart: new Date(currentYear, currentMonth, todayDate + 2, 13, 15),
                dateEnd: new Date(currentYear, currentMonth, todayDate + 2, 16, 15),
                backgroundColor: '#039BE5'
            }
        ],
        currentTimeIndicator = true,
        shadeUntilCurrentTime = true,
        view = 'day',
        views = ['day', 'week', 'month', 'timelineDay', 'timelineWeek', 'timelineMonth'],
        firstDayOfWeek = 1;

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Welcome to Next.js!</h1>

                <DynamicScheduler
                    className={styles.scheduler}
                    id="scheduler"
                    currentTimeIndicator={currentTimeIndicator}
                    shadeUntilCurrentTime={shadeUntilCurrentTime}
                    dataSource={dataSource}
                    view={view}
                    views={views}
                    firstDayOfWeek={firstDayOfWeek}
                />
            </main>
        </div>
    );
}